{% set name = "opentelemetry-exporter-otlp-proto-grpc" %}
{% set version = "1.36.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_exporter_otlp_proto_grpc-{{ version }}.tar.gz
  sha256: b281afbf7036b325b3588b5b6c8bb175069e3978d1bd24071f4a59d04c1e5bbf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - deprecated >=1.2.6
    - googleapis-common-protos ~=1.57
    - grpcio <2.0.0,>=1.66.2
    - opentelemetry-api ~=1.15
    - opentelemetry-proto ==1.36.0
    - opentelemetry-sdk ~=1.36.0
    - opentelemetry-exporter-otlp-proto-common ==1.36.0
  # NOTE backoff only required for py<37 but pip checks fails without it
    #- backoff >=1.10.0,<3.0.0
    # - typing_extensions >=4.5.0
    # - typing_extensions >=4.5.0
    # - typing_extensions >=4.6.0
    # - typing_extensions >=4.6.0

test:
  imports:
    - opentelemetry
    - opentelemetry.exporter
    - opentelemetry.exporter.otlp.proto.grpc
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-otlp-proto-grpc
  summary: OpenTelemetry Collector Protobuf over gRPC Exporter
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
    - conda-forge/opentelemetry-api
    - conda-forge/opentelemetry-proto
    - conda-forge/opentelemetry-sdk
    - conda-forge/opentelemetry-exporter-otlp-proto-common
