{% set name = "opentelemetry-exporter-otlp-proto-grpc" %}
{% set version = "1.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_exporter_otlp_proto_grpc-{{ version }}.tar.gz
  sha256: e69261b4da8cbaa42d9b5f1cff4fcebbf8a3c02f85d69a8aea698312084f4180

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - deprecated >=1.2.6
    - googleapis-common-protos >=1.52,<2.0
    - grpcio >=1.0.0,<2.0.0
    - opentelemetry-api >=1.15,<2.0
    - opentelemetry-proto =={{ version }}
    - opentelemetry-sdk =={{ version }}
    - opentelemetry-exporter-otlp-proto-common =={{ version }}
  # NOTE backoff only required for py<37 but pip checks fails without it
    - backoff >=1.10.0,<2.0.0

test:
  imports:
    - opentelemetry
    - opentelemetry.exporter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-otlp-proto-grpc
  summary: OpenTelemetry Collector Protobuf over gRPC Exporter
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
