{% set name = "opentelemetry-exporter-otlp-proto-grpc" %}
{% set version = "1.29.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_exporter_otlp_proto_grpc-{{ version }}.tar.gz
  sha256: 3d324d07d64574d72ed178698de3d717f62a059a93b6b7685ee3e303384e73ea

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - deprecated >=1.2.6
    - googleapis-common-protos >=1.52,<2.dev0
    - grpcio >=1.63.2,<2.0.0
    - opentelemetry-api >=1.15,<2.dev0
    - opentelemetry-proto =={{ version }}
    - opentelemetry-sdk >={{ version }},<1.30.dev0
    - opentelemetry-exporter-otlp-proto-common =={{ version }}
  # NOTE backoff only required for py<37 but pip checks fails without it
    #- backoff >=1.10.0,<3.0.0

test:
  imports:
    - opentelemetry
    - opentelemetry.exporter
    - opentelemetry.exporter.otlp.proto.grpc
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-otlp-proto-grpc
  summary: OpenTelemetry Collector Protobuf over gRPC Exporter
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
    - conda-forge/opentelemetry-api
    - conda-forge/opentelemetry-proto
    - conda-forge/opentelemetry-sdk
    - conda-forge/opentelemetry-exporter-otlp-proto-common
